#!/usr/bin/env python3
"""Archive the observed startup and integrity failures without utility scores."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil


def read(path):
    return json.loads(path.read_text())


def main(raw, out):
    tools = Path(__file__).resolve().parent
    protocol = read(tools / "protocol.json")
    runtime = read(raw / "runtime.json")
    audit = read(raw / "audit.json")
    status = read(raw / "federation-status.json")
    contract = read(raw / "node-contract.json")
    initial = read(raw / "initial-capture.json")
    logs = read(raw / "public-node-diagnostics.json")
    exact = "DSFLOWER SECURITY: package '_remote_module_non_scriptable' is not in pinned_packages.json (default-deny)."
    assert status["status"] == "failed" and status["cleanup_ok"]
    assert initial["seed"] == protocol["seeds"][0]
    assert len(logs) == 3 and all(exact in str(site) for site in logs)
    assert audit["test_accessed"] is False
    out.mkdir(parents=True, exist_ok=True)
    for name in ("runtime.json", "audit.json", "preflight.json", "startup-attempts.json",
                 "node-contract.json", "initial-capture.json", "public-node-diagnostics.json", "federation-status.json"):
        shutil.copyfile(raw / name, out / name)
    blocker = {"phase": "node runtime import guard", "exact_node_error": exact,
               "outer_error": status["error"], "affected_sites": ["site1", "site2", "site3"],
               "interpretation": "The pinned release integrity guard rejects a module generated by the installed PyTorch runtime. No guard or pin-map alteration was attempted.",
               "scope": "Observed with torch 2.6.0+cu124, Opacus 1.6.0 and Flower 1.31.0; this is not a claim that every permissible dependency combination fails.",
               "gru_not_attempted_reason": "Shared PyTorch generated-module import failure; no LSTM-specific architecture failure was observed.",
               "test_accessed": False, "completed_node_updates_observed": 0, "released_model": False,
               "acceptance_diagnostic": "not evaluated"}
    files = []
    for epsilon in (1, 4, 8):
        reps = []
        for seed in protocol["seeds"]:
            attempted = epsilon == 1 and seed == protocol["seeds"][0]
            reps.append({"seed": seed, "status": "blocked" if attempted else "not_run",
                         "federated_dp": None, "central": None, "trivial": None, "pooled_dp": None,
                         "gap_macro_auc": None, "completed_replicate_wall_clock_s": None,
                         "attempt_elapsed_s": status["elapsed_s"] if attempted else None,
                         "earlier_startup_attempts": read(raw / "startup-attempts.json") if attempted else [],
                         "node_policy_reported": contract["policies"] if attempted else None})
        cell = {"schema": "dsflower-sequence-campaign-v1", "status": "blocked" if epsilon == 1 else "not_run",
                "generated_at": datetime.now(timezone.utc).isoformat(), "contract": "pytorch_lstm", "epsilon": epsilon,
                "runtime": runtime, "dataset": audit,
                "test_split": {"policy": "official subject-disjoint split", "expected_subjects": 9,
                               "expected_windows": 2947, "counts_are_documented_not_observed": True, "read": False},
                "protocol": protocol, "protocol_sha256": hashlib.sha256((tools / "protocol.json").read_bytes()).hexdigest(),
                "privacy_requested": {"epsilon": epsilon, "delta": 1e-6, "unit": "patient", "patient_column": "subject", "clipping_norm": 1},
                "full_node_contract_reported": contract if epsilon == 1 else None,
                "per_replicate": reps, "summary": {"n_completed": 0, "central_mean_sd": None,
                     "federated_mean_sd": None, "trivial_mean_sd": None, "gap_macro_auc_mean_sd": None},
                "blocker": blocker, "acceptance_diagnostic": {"status": "not_evaluated", "passed": None}}
        name = f"pilot_uci_har_pytorch_lstm_eps{epsilon}.json"
        path = out / name
        path.write_text(json.dumps(cell, indent=2, allow_nan=False) + "\n")
        files.append({"file": name, "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                      "epsilon": epsilon, "status": cell["status"], "completed_replicates": 0})
    summary = {"schema": "dsflower-sequence-summary-v1", "status": "blocked", "contract": "pytorch_lstm",
               "dataset": audit["name"], "n_train_windows": audit["n_train_windows"], "n_train_subjects": 21,
               "n_per_site": audit["n_per_site"], "seeds": protocol["seeds"], "rounds_planned": 5,
               "attempted_replicates": 1, "completed_replicates": 0, "held_out_scores": None,
               "blocker": blocker, "cells": files, "runtime": runtime,
               "synthetic_preflight_passed": True,
               "synthetic_preflight_scope": "Direct GPU DP update passed outside the full node import guard; not a federation or HAR utility result.",
               "pod_left_running": True}
    (out / "summary.json").write_text(json.dumps(summary, indent=2, allow_nan=False) + "\n")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--raw", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()
    main(args.raw, args.out)
