#!/usr/bin/env Rscript

result_path <- file.path("inst", "extdata", "dsflower_method_validation_results.json")
if (!file.exists(result_path)) {
  stop("Run inst/demos/validate_methods.R before generating validation vignettes.", call. = FALSE)
}

validation <- jsonlite::fromJSON(result_path)
results <- validation$results
vision_result_path <- file.path("inst", "extdata", "dsflower_vision_validation_results.json")
vision_validation <- if (file.exists(vision_result_path)) {
  jsonlite::fromJSON(vision_result_path)
} else {
  NULL
}
vision_results <- if (!is.null(vision_validation)) vision_validation$results else NULL

slug <- function(method) gsub("_", "-", method, fixed = TRUE)

write_lines <- function(path, lines) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path, useBytes = TRUE)
}

method_vignette <- function(method) {
  title <- paste0("Validation: ", method)
  c(
    "---",
    paste0("title: \"", title, "\""),
    "output: rmarkdown::html_vignette",
    "vignette: >",
    paste0("  %\\VignetteIndexEntry{", title, "}"),
    "  %\\VignetteEngine{knitr::rmarkdown}",
    "  %\\VignetteEncoding{UTF-8}",
    "---",
    "",
    "```{r, include=FALSE}",
    "knitr::opts_chunk$set(collapse = TRUE, comment = '#>')",
    paste0("method_id <- \"", method, "\""),
    "paths <- c(",
    "  file.path('..', 'inst', 'extdata', 'dsflower_method_validation_results.json'),",
    "  file.path('inst', 'extdata', 'dsflower_method_validation_results.json'),",
    "  system.file('extdata', 'dsflower_method_validation_results.json', package = 'dsFlowerClient')",
    ")",
    "result_path <- paths[nzchar(paths) & file.exists(paths)][1]",
    "validation <- jsonlite::fromJSON(result_path)",
    "results <- validation$results",
    "row <- results[results$method == method_id, , drop = FALSE]",
    "fmt <- function(x) {",
    "  if (length(x) == 0 || is.null(x) || is.na(x)) return('NA')",
    "  if (is.numeric(x)) return(format(round(x, 4), nsmall = 4, trim = TRUE))",
    "  as.character(x)",
    "}",
    "```",
    "",
    "This vignette records a live validation of the method against a centralized baseline.",
    "The federated run used three Opal/Rock nodes and the same pooled synthetic",
    "validation cohort was used for the local baseline. The purpose is method-path",
    "validation: data staging, template verification, Flower execution, result",
    "persistence, and cleanup. It is not a clinical performance benchmark.",
    "",
    "```{r}",
    "overview <- data.frame(",
    "  Field = c(",
    "    'method', 'task', 'target', 'n_features', 'rounds',",
    "    'centralized_metric', 'centralized_loss', 'centralized_accuracy',",
    "    'federated_status', 'federated_loss', 'federated_n_failures',",
    "    'delta_loss', 'acceptance_max_loss_ratio',",
    "    'acceptance_max_loss_margin', 'acceptable_loss',",
    "    'validation_status'",
    "  ),",
    "  Value = c(",
    "    row$method, row$task, row$target, row$n_features, row$rounds,",
    "    row$centralized_metric, fmt(row$centralized_loss), fmt(row$centralized_accuracy),",
    "    row$federated_status, fmt(row$federated_loss), fmt(row$federated_n_failures),",
    "    fmt(row$delta_loss), fmt(row$acceptance_max_loss_ratio),",
    "    fmt(row$acceptance_max_loss_margin), row$acceptable_loss,",
    "    row$validation_status",
    "  )",
    ")",
    "knitr::kable(overview)",
    "```",
    "",
    paste0("```{r, fig.width=5.5, fig.height=3.2, fig.alt=\"Bar chart comparing centralized and federated validation loss for ", method, ".\"}"),
    "loss_df <- data.frame(",
    "  mode = c('Centralized', 'Federated'),",
    "  loss = c(row$centralized_loss, row$federated_loss)",
    ")",
    "loss_df <- loss_df[is.finite(loss_df$loss), , drop = FALSE]",
    "if (nrow(loss_df) > 0 && requireNamespace('ggplot2', quietly = TRUE)) {",
    "  ggplot2::ggplot(loss_df, ggplot2::aes(x = mode, y = loss, fill = mode)) +",
    "    ggplot2::geom_col(width = 0.65, show.legend = FALSE) +",
    "    ggplot2::labs(x = NULL, y = row$centralized_metric[[1]], title = method_id) +",
    "    ggplot2::theme_minimal(base_size = 11)",
    "} else {",
    "  plot.new()",
    "  text(0.5, 0.5, 'No federated loss available for this method')",
    "}",
    "```",
    "",
    "## Step-By-Step Run Output",
    "",
    "The following chunks print the audit trail for the actual run stored in",
    "`inst/extdata/dsflower_method_validation_results.json`. They are evaluated",
    "when pkgdown renders the vignette, so the page shows the concrete centralized",
    "and federated outputs rather than only describing the API shape.",
    "",
    "```{r step-inputs}",
    "target_cols <- trimws(strsplit(row$target, ',', fixed = TRUE)[[1]])",
    "site_table_paths <- validation$table_paths",
    "input_trace <- data.frame(",
    "  step = c(",
    "    '1. Build validation cohort',",
    "    '2. Split across sites',",
    "    '3. Select task target',",
    "    '4. Select model features',",
    "    '5. Materialize Opal tables'",
    "  ),",
    "  observed_output = c(",
    "    paste(validation$n_total, 'synthetic rows generated for this suite'),",
    "    paste(validation$n_sites, 'sites x', validation$n_per_site, 'rows per site'),",
    "    paste(target_cols, collapse = ', '),",
    "    paste(row$n_features, 'features:', paste0('x1..x', row$n_features)),",
    "    paste(site_table_paths, collapse = '\\n')",
    "  ),",
    "  stringsAsFactors = FALSE",
    ")",
    "knitr::kable(input_trace)",
    "```",
    "",
    "```{r centralized-output}",
    "centralized_output <- data.frame(",
    "  step = c(",
    "    '1. Load pooled validation cohort',",
    "    '2. Train centralized baseline',",
    "    '3. Evaluate centralized baseline'",
    "  ),",
    "  observed_output = c(",
    "    paste(validation$n_total, 'pooled rows with', row$n_features, 'features'),",
    "    paste('status =', row$centralized_status, '| metric =', row$centralized_metric),",
    "    paste('loss =', fmt(row$centralized_loss),",
    "          '| accuracy =', fmt(row$centralized_accuracy))",
    "  ),",
    "  stringsAsFactors = FALSE",
    ")",
    "knitr::kable(centralized_output)",
    "```",
    "",
    "```{r centralized-console}",
    "cat(",
    "  sprintf('[centralized] method: %s\\n', row$method),",
    "  sprintf('[centralized] task: %s | target: %s | features: %s\\n',",
    "          row$task, row$target, paste0('x1..x', row$n_features)),",
    "  sprintf('[centralized] status: %s\\n', row$centralized_status),",
    "  sprintf('[centralized] %s: %.4f\\n', row$centralized_metric, row$centralized_loss),",
    "  sprintf('[centralized] accuracy: %s\\n', fmt(row$centralized_accuracy)),",
    "  sep = ''",
    ")",
    "```",
    "",
    "```{r dsflower-output}",
    "max_allowed_loss <- row$centralized_loss * row$acceptance_max_loss_ratio +",
    "  row$acceptance_max_loss_margin",
    "dsflower_output <- data.frame(",
    "  step = c(",
    "    '1. Login through DataSHIELD',",
    "    '2. Prepare server-side dsFlower nodes',",
    "    '3. Start Flower SuperLink/SuperNodes',",
    "    '4. Run federated training',",
    "    '5. Collect metrics and cleanup'",
    "  ),",
    "  observed_output = c(",
    "    paste(validation$n_sites, 'Opal/Rock nodes connected'),",
    "    paste('template =', row$method, '| privacy =', validation$privacy_profile),",
    "    paste('federated_run_id =', row$federated_run_id),",
    "    paste('rounds =', row$rounds, '| federated_loss =', fmt(row$federated_loss),",
    "          '| client_failures =', fmt(row$federated_n_failures)),",
    "    paste('federated_status =', row$federated_status,",
    "          '| validation_status =', row$validation_status)",
    "  ),",
    "  stringsAsFactors = FALSE",
    ")",
    "knitr::kable(dsflower_output)",
    "```",
    "",
    "```{r dsflower-console}",
    "cat(",
    "  sprintf('[dsFlower] DataSHIELD login: %s nodes\\n', validation$n_sites),",
    "  sprintf('[dsFlower] table paths: %s\\n', paste(site_table_paths, collapse = ' | ')),",
    "  sprintf('[dsFlower] model: %s | strategy: fedavg | rounds: %s\\n',",
    "          row$method, row$rounds),",
    "  sprintf('[dsFlower] run id: %s\\n', row$federated_run_id),",
    "  sprintf('[Flower] aggregate_fit/evaluate: clients=%s failures=%s\\n',",
    "          validation$n_sites, fmt(row$federated_n_failures)),",
    "  sprintf('[Flower] final federated loss: %.4f\\n', row$federated_loss),",
    "  sprintf('[cleanup] status: %s\\n', row$federated_status),",
    "  sep = ''",
    ")",
    "```",
    "",
    "```{r acceptance-output}",
    "acceptance_output <- data.frame(",
    "  centralized_loss = row$centralized_loss,",
    "  federated_loss = row$federated_loss,",
    "  max_allowed_loss = max_allowed_loss,",
    "  federated_n_failures = row$federated_n_failures,",
    "  acceptable_loss = row$acceptable_loss,",
    "  validation_status = row$validation_status",
    ")",
    "knitr::kable(acceptance_output, digits = 4)",
    "```",
    "",
    "## Inline Execution Path",
    "",
    "The validation row above was generated by running this method through the",
    "same inline DataSHIELD/Flower flow shown below. The vignette does not",
    "delegate execution to an external launcher; the rendered result is loaded",
    "from the versioned JSON artifact written by the live run.",
    "",
    "```{r opal-config, eval=FALSE}",
    "library(DSI)",
    "library(DSOpal)",
    "library(dsFlowerClient)",
    "library(opalr)",
    "",
    "opal_urls <- trimws(strsplit(Sys.getenv(",
    "  'DSFLOWER_OPAL_URLS',",
    "  'https://localhost:8443,https://localhost:8444,https://localhost:8445'",
    "), ',', fixed = TRUE)[[1]])",
    "opal_users <- rep(Sys.getenv('OPAL_USER', 'administrator'), length(opal_urls))",
    "opal_passwords <- rep(Sys.getenv('OPAL_PASSWORD', 'admin123'), length(opal_urls))",
    "project <- Sys.getenv('DSFLOWER_DEMO_PROJECT', 'dsflower_demo')",
    "```",
    "",
    "```{r synthetic-cohort, eval=FALSE}",
    "set.seed(4242)",
    "n_sites <- length(opal_urls)",
    "n_per_site <- validation$n_per_site",
    "n <- n_sites * n_per_site",
    "p <- row$n_features",
    "x <- scale(matrix(stats::rnorm(n * p), nrow = n, ncol = p))",
    "colnames(x) <- paste0('x', seq_len(p))",
    "",
    "cohort <- data.frame(id = sprintf('mv_%04d', seq_len(n)), x)",
    "cohort$outcome <- as.integer(0.9 * x[, 1] - 0.7 * x[, 2] +",
    "                             0.45 * x[, 3] + stats::rnorm(n, sd = 0.4) > 0)",
    "cohort$y <- 1.4 * x[, 1] - 1.1 * x[, 4] + 0.5 * x[, 7] +",
    "            stats::rnorm(n, sd = 0.45)",
    "cohort$class3 <- as.integer(cut(x[, 2] - 0.5 * x[, 5] + 0.35 * x[, 8],",
    "                               breaks = stats::quantile(",
    "                                 x[, 2] - 0.5 * x[, 5] + 0.35 * x[, 8],",
    "                                 probs = c(0, 1 / 3, 2 / 3, 1)",
    "                               ), include.lowest = TRUE, labels = FALSE)) - 1L",
    "cohort$label_a <- as.integer(x[, 1] + x[, 6] + stats::rnorm(n, sd = 0.5) > 0)",
    "cohort$label_b <- as.integer(-x[, 2] + x[, 7] + stats::rnorm(n, sd = 0.5) > 0)",
    "cohort$label_c <- as.integer(x[, 3] - x[, 8] + stats::rnorm(n, sd = 0.5) > 0)",
    "cohort$count <- stats::rpois(n, lambda = exp(pmin(pmax(0.2 + 0.35 * x[, 1] -",
    "                                                    0.25 * x[, 9], -2), 2)))",
    "cohort$time <- exp(2.0 - 0.25 * x[, 1] + 0.18 * x[, 5] +",
    "                   stats::rnorm(n, sd = 0.35))",
    "cohort$event <- as.integer(stats::runif(n) > 0.35)",
    "cohort$event_type <- ifelse(cohort$event == 0L, 0L,",
    "                            ifelse(0.6 * x[, 10] - 0.45 * x[, 11] > 0, 1L, 2L))",
    "cohort$site <- rep(seq_len(n_sites), length.out = n)",
    "```",
    "",
    "```{r upload-and-connect, eval=FALSE}",
    "table_paths <- character(n_sites)",
    "for (i in seq_len(n_sites)) {",
    "  opal <- opalr::opal.login(",
    "    username = opal_users[[i]], password = opal_passwords[[i]],",
    "    url = opal_urls[[i]],",
    "    opts = list(ssl_verifyhost = 0L, ssl_verifypeer = 0L)",
    "  )",
    "  table_name <- paste0('method_validation_', method_id, '_site', i)",
    "  site_data <- cohort[cohort$site == i, setdiff(names(cohort), 'site'), drop = FALSE]",
    "  opalr::opal.table_save(opal, site_data, project = project, table = table_name,",
    "                         id.name = 'id', policy = 'generate',",
    "                         overwrite = TRUE, force = TRUE)",
    "  table_paths[[i]] <- paste(project, table_name, sep = '.')",
    "  opalr::opal.logout(opal)",
    "}",
    "",
    "builder <- DSI::newDSLoginBuilder()",
    "for (i in seq_len(n_sites)) {",
    "  builder$append(server = paste0('opal', i), url = opal_urls[[i]],",
    "                 user = opal_users[[i]], password = opal_passwords[[i]],",
    "                 table = table_paths[[i]], driver = 'OpalDriver')",
    "}",
    "conns <- DSI::datashield.login(builder$build(), assign = TRUE, symbol = 'D')",
    "```",
    "",
    "```{r federated-fit, eval=FALSE}",
    "targets <- trimws(strsplit(row$target, ',', fixed = TRUE)[[1]])",
    "features <- paste0('x', seq_len(row$n_features))",
    "",
    "fit <- ds.flower.fit(",
    "  conns,",
    "  symbol = 'D',",
    "  target = targets,",
    "  features = features,",
    "  model = row$method,",
    "  strategy = 'fedavg',",
    "  privacy = 'sandbox_open',",
    "  rounds = row$rounds,",
    "  task = row$task",
    ")",
    "",
    "post_caps <- DSI::datashield.aggregate(",
    "  conns, as.symbol('flowerGetCapabilitiesDS')",
    ")",
    "DSI::datashield.logout(conns)",
    "```",
    "",
    "```{r acceptance-check, eval=FALSE}",
    "history <- fit$history",
    "federated_loss <- tail(stats::na.omit(as.numeric(history$loss)), 1)",
    "federated_failures <- max(as.numeric(history$n_failures), na.rm = TRUE)",
    "acceptable <- federated_failures == 0 &&",
    "  federated_loss <= row$centralized_loss * row$acceptance_max_loss_ratio +",
    "                    row$acceptance_max_loss_margin",
    "acceptable",
    "```",
    "",
    "```{r}",
    "if (nzchar(row$error)) cat(row$error)",
    "```"
  )
}

article_link_lines <- function(methods, vision_methods = character()) {
  lines <- c("Per-method vignettes:", "")
  lines <- c(lines, paste0("- [", methods, "](validation-", slug(methods), ".html)"))
  if (length(vision_methods)) {
    lines <- c(lines, "", "Vision method vignettes:", "")
    lines <- c(lines, paste0(
      "- [", vision_methods, "](validation-vision-", slug(vision_methods), ".html)"
    ))
  }
  lines
}

overview_vignette <- function(methods, vision_methods = character()) {
  c(
    "---",
    "title: \"All Method Validation Overview\"",
    "output: rmarkdown::html_vignette",
    "vignette: >",
    "  %\\VignetteIndexEntry{All Method Validation Overview}",
    "  %\\VignetteEngine{knitr::rmarkdown}",
    "  %\\VignetteEncoding{UTF-8}",
    "---",
    "",
    "```{r, include=FALSE}",
    "knitr::opts_chunk$set(collapse = TRUE, comment = '#>')",
    "method_paths <- c(",
    "  file.path('..', 'inst', 'extdata', 'dsflower_method_validation_results.json'),",
    "  file.path('inst', 'extdata', 'dsflower_method_validation_results.json'),",
    "  system.file('extdata', 'dsflower_method_validation_results.json', package = 'dsFlowerClient')",
    ")",
    "method_result_path <- method_paths[nzchar(method_paths) & file.exists(method_paths)][1]",
    "method_validation <- jsonlite::fromJSON(method_result_path)",
    "method_results <- method_validation$results",
    "vision_paths <- c(",
    "  file.path('..', 'inst', 'extdata', 'dsflower_vision_validation_results.json'),",
    "  file.path('inst', 'extdata', 'dsflower_vision_validation_results.json'),",
    "  system.file('extdata', 'dsflower_vision_validation_results.json', package = 'dsFlowerClient')",
    ")",
    "vision_result_path <- vision_paths[nzchar(vision_paths) & file.exists(vision_paths)][1]",
    "vision_validation <- if (!is.na(vision_result_path)) jsonlite::fromJSON(vision_result_path) else NULL",
    "vision_results <- if (!is.null(vision_validation)) vision_validation$results else NULL",
    "method_display <- data.frame(",
    "  suite = 'tabular_sequence_survival',",
    "  method = method_results$method,",
    "  task = method_results$task,",
    "  centralized_metric = method_results$centralized_metric,",
    "  centralized_loss = method_results$centralized_loss,",
    "  federated_status = method_results$federated_status,",
    "  federated_loss = method_results$federated_loss,",
    "  delta_loss = method_results$delta_loss,",
    "  acceptable_loss = method_results$acceptable_loss,",
    "  validation_status = method_results$validation_status,",
    "  stringsAsFactors = FALSE",
    ")",
    "vision_display <- if (!is.null(vision_results)) data.frame(",
    "  suite = 'vision',",
    "  method = vision_results$method,",
    "  task = vision_results$task,",
    "  centralized_metric = vision_results$centralized_metric,",
    "  centralized_loss = vision_results$centralized_loss,",
    "  federated_status = vision_results$federated_status,",
    "  federated_loss = vision_results$federated_loss,",
    "  delta_loss = vision_results$delta_loss,",
    "  acceptable_loss = vision_results$acceptable_loss,",
    "  validation_status = vision_results$validation_status,",
    "  stringsAsFactors = FALSE",
    ") else method_display[0, ]",
    "results <- rbind(method_display, vision_display)",
    "```",
    "",
    "This macro-vignette summarizes the live dsFlower validation suite across",
    "tabular, sequence, survival, XGBoost, image-classification, and segmentation",
    "templates. Each method has its own vignette, and each federated run is",
    "compared with a centralized baseline trained on the corresponding pooled",
    "synthetic cohort.",
    "",
    "The suite is deliberately a functional and numerical sanity check, not a",
    "privacy claim and not a clinical benchmark. It uses `sandbox_open` so that",
    "per-node diagnostics can be observed during development. Production studies",
    "should use the stricter DataSHIELD privacy profiles. XGBoost is validated",
    "in this trusted demo mode; profiles that require Secure Aggregation still",
    "enforce SecAgg before execution.",
    "",
    "```{r}",
    "summary_table <- data.frame(",
    "  suite = c('tabular_sequence_survival', 'vision'),",
    "  generated_at = c(method_validation$generated_at, if (!is.null(vision_validation)) vision_validation$generated_at else NA),",
    "  privacy_profile = c(method_validation$privacy_profile, if (!is.null(vision_validation)) vision_validation$privacy_profile else NA),",
    "  n_sites = c(method_validation$n_sites, if (!is.null(vision_validation)) vision_validation$n_sites else NA),",
    "  n_total = c(method_validation$n_total, if (!is.null(vision_validation)) vision_validation$n_total else NA),",
    "  secagg_supported = c(method_validation$secagg_supported, NA),",
    "  stringsAsFactors = FALSE",
    ")",
    "knitr::kable(summary_table)",
    "```",
    "",
    "```{r}",
    "knitr::kable(results)",
    "```",
    "",
    "```{r, fig.width=8, fig.height=5, fig.alt=\"Horizontal bar chart of federated minus centralized loss by method.\"}",
    "plot_df <- results[is.finite(results$delta_loss), , drop = FALSE]",
    "if (nrow(plot_df) > 0 && requireNamespace('ggplot2', quietly = TRUE)) {",
    "  plot_df$label <- paste(plot_df$suite, plot_df$method, sep = ': ')",
    "  ggplot2::ggplot(plot_df, ggplot2::aes(x = stats::reorder(label, delta_loss), y = delta_loss, fill = task)) +",
    "    ggplot2::geom_hline(yintercept = 0, linewidth = 0.3, color = 'grey40') +",
    "    ggplot2::geom_col(width = 0.7) +",
    "    ggplot2::coord_flip() +",
    "    ggplot2::labs(x = NULL, y = 'Federated loss - centralized loss') +",
    "    ggplot2::theme_minimal(base_size = 11)",
    "}",
    "```",
    "",
    article_link_lines(methods, vision_methods),
    "",
    "The vision-specific overview remains available at",
    "[Vision Method Validation Overview](validation-vision-overview.html).",
    "",
    "The full suite is produced by repeating the inline Opal/DataSHIELD/Flower",
    "workflow shown in each per-method vignette for every method listed above.",
    "The persisted JSON artifacts are the audit trail consumed by this",
    "pkgdown site."
  )
}

for (method in results$method) {
  path <- file.path("vignettes", paste0("validation-", slug(method), ".Rmd"))
  write_lines(path, method_vignette(method))
}

write_lines(file.path("vignettes", "validation-overview.Rmd"),
            overview_vignette(
              results$method,
              if (!is.null(vision_results)) vision_results$method else character()
            ))

message("Generated ", length(results$method) + 1L, " validation vignettes.")
